enable using mouse on the radial menu
fgsfdsfgs/perfect_dark pull request #108
Opened 2023-08-27 20:53 UTC by rafccq

Solves #107

2023-08-27 22:34 UTC, fgsfdsfgs commented
What's the whole current device thing for? Is it not enough to just check if `dx`/`dy` are non-zero, like the rest of the input code does?

2023-08-28 01:51 UTC, NeonNyan commented
I'd really like to be able to play with a left-analog stick and mouse for aiming. This would explicitly break that.

When the check is removed, you can't move the radial dial with the xbox sticks after using the mouse unless you close and re-open the radial menu.

2023-08-28 04:00 UTC, NeonNyan commented
> I'd really like to be able to play with a left-analog stick and mouse for aiming. This would explicitly break that.
> 
> When the check is removed, you can't move the radial dial with the xbox sticks after using the mouse unless you close and re-open the radial menu.

Also it's not just this one case: it's preferable to map the steam deck gyro / stick / trackpads to the mouse, which would cause unfriendly behavior unless key presses are being handled correctly in the game code.

2023-08-28 09:20 UTC, fgsfdsfgs commented
That can be solved by just adding up movement from the sticks and the mouse instead of making them exclusive. Let me see what I can do.

2023-08-28 09:30 UTC, rafccq commented
@fgsfdsfgs I didn't use dx/dy to keep the slot selected, and not return to the center if there was no movement.
I added the device thing so the game detects the last device you used, and use only that one for the radial menu input, but
yes sounds better to just add the movements of mouse and sticks, I didn't think of it. 
That will make it work with control schemes such as the ones mentioned by @NeonNyan

2023-08-28 09:48 UTC, fgsfdsfgs commented
Something like this would probably work fine, though it does need some tuning.
[radial-mouse.patch](https://github.com/fgsfdsfgs/perfect_dark/files/12453099/radial-mouse.patch)

2023-08-28 09:54 UTC, rafccq commented
Thanks, I'll test it out and tune if needed.

2023-08-28 23:57 UTC, AXDOOMER commented
The new code doesn't use the same indentation as the rest of the file. This should be fixed.

2023-08-29 00:00 UTC, AXDOOMER requested changes

2023-08-29 00:00 UTC, AXDOOMER commented on port/src/input.c
> +	 	// rescale to fit the non-deadzone range
This new random whitespace should be removed.

2023-08-29 00:00 UTC, AXDOOMER commented on src/game/activemenutick.c
> +#endif
The new code doesn't use the same indentation as the rest of the file. This should be fixed.

2023-08-29 00:00 UTC, AXDOOMER commented on src/game/activemenutick.c
> +#endif
This code is also not indented the same as the rest of the code. This file uses tabs put your editor is inserting spaces.

2023-08-29 00:00 UTC, AXDOOMER commented on src/include/types.h
> +#endif
Also not indented as the rest.

2023-08-29 07:23 UTC, fgsfdsfgs commented
The whitespace issues are because you're using spaces instead of tabs, unlike the rest of the code.

2023-08-30 10:00 UTC, merged